---
name: Tie-ListKeyedHash
version: 1.01
author:
  - Benjamin Franz <snowhare@nihongo.org>
abstract: A system allowing the use of anonymous arrays as keys to a hash.
license: perl
requires:
  Test::More: 0
provides:
  Tie::ListKeyedHash:
    file: lib/Tie/ListKeyedHash.pm
    version: 1.01
generated_by: Module::Build version 0.261
